#!/bin/bash
# =====================================================
# Voyage Sorgun — PocketBase Aktivite Seed
# 72 aktivite: daytime x24, kids x24, evening x24
# =====================================================

PB_URL="https://hotel-data.voyagestars.com"
PB_TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzUwODMxOTUsImlkIjoiZHZiOGx2czJkYm03MGx6IiwidHlwZSI6ImFkbWluIn0.Eyi5AVS7dVGZClOkKm3uJcsdO5y9XFnoyrh7lmI6_j0"
COL="activities"

send() {
  local name="$1" start="$2" end="$3" hour=$4 minute=$5 icon="$6" venue="$7" slot="$8"
  local code
  code=$(curl -s -o /dev/null -w "%{http_code}" \
    -X POST "${PB_URL}/api/collections/${COL}/records" \
    -H "Authorization: Bearer ${PB_TOKEN}" \
    -H "Content-Type: application/json" \
    -d "{\"name\":\"${name}\",\"start\":\"${start}\",\"end\":\"${end}\",\"hour\":${hour},\"minute\":${minute},\"icon\":\"${icon}\",\"venue\":\"${venue}\",\"venue_key\":\"\",\"schedule_slot\":\"${slot}\",\"cycle_day\":-1}")
  printf "%-10s %s  %-30s → HTTP %s\n" "$slot" "$start" "$name" "$code"
}

echo "════════════════════════════════════════"
echo "  DAYTIME  (24 aktivite)"
echo "════════════════════════════════════════"
send "Midnight Yoga"           "00:00" "01:00"  0 0 "🧘" "Beach Stage · Sunrise Deck" "daytime"
send "Sunrise Stretch"         "01:00" "02:00"  1 0 "🌅" "Panorama Deck"              "daytime"
send "Early Swim"              "02:00" "03:00"  2 0 "🏊" "Main Pool"                  "daytime"
send "Night Walk Tour"         "03:00" "04:00"  3 0 "🌙" "Beach Stage · Sunrise Deck" "daytime"
send "Pre-Dawn Meditation"     "04:00" "05:00"  4 0 "✨" "Panorama Deck"              "daytime"
send "Sunrise Yoga"            "05:00" "06:00"  5 0 "🧘" "Beach Stage · Sunrise Deck" "daytime"
send "Morning Stretch"         "06:00" "07:00"  6 0 "🤸" "Beach Stage · Sunrise Deck" "daytime"
send "Beach Jogging"           "07:00" "08:00"  7 0 "🏃" "Beach Stage · Sunrise Deck" "daytime"
send "Aqua Aerobics"           "08:00" "09:00"  8 0 "💧" "Main Pool"                  "daytime"
send "Pilates"                 "09:00" "10:00"  9 0 "🤸" "Beach Stage · Sunrise Deck" "daytime"
send "Beach Volleyball"        "10:00" "11:00" 10 0 "🏐" "Beach Court 1 & 2"          "daytime"
send "Animation Show"          "11:00" "12:00" 11 0 "🎭" "Amphitheatre"               "daytime"
send "Foam Party"              "12:00" "13:00" 12 0 "🫧" "Aquapark Zone"              "daytime"
send "Pool Games"              "13:00" "14:00" 13 0 "🏊" "Main Pool"                  "daytime"
send "Archery"                 "14:00" "15:00" 14 0 "🎯" "Sports Zone A"              "daytime"
send "Table Tennis"            "15:00" "16:00" 15 0 "🏓" "Sports Zone B"              "daytime"
send "Tennis Open"             "16:00" "17:00" 16 0 "🎾" "Court 1"                    "daytime"
send "Happy Hour"              "17:00" "18:00" 17 0 "🍹" "Sunset Bar · Lobby Bar"     "daytime"
send "Sunset Cocktail Party"   "18:00" "19:00" 18 0 "🌅" "Panorama Deck"              "daytime"
send "Poolside Music"          "19:00" "20:00" 19 0 "🎵" "Main Pool"                  "daytime"
send "Outdoor Cinema"          "20:00" "21:00" 20 0 "🎬" "Amphitheatre"               "daytime"
send "Stargazing Walk"         "21:00" "22:00" 21 0 "⭐" "Beach Stage · Sunrise Deck" "daytime"
send "Night Swim"              "22:00" "23:00" 22 0 "🌊" "Main Pool"                  "daytime"
send "Midnight Lounge"         "23:00" "00:00" 23 0 "🍹" "Sunset Bar · Lobby Bar"     "daytime"

echo ""
echo "════════════════════════════════════════"
echo "  KIDS  (24 aktivite)"
echo "════════════════════════════════════════"
send "Goodnight Story Time"    "00:00" "01:00"  0 0 "🌙" "Mini Club · Deck C"         "kids"
send "Dream & Draw"            "01:00" "02:00"  1 0 "🎨" "Mini Club · Deck C"         "kids"
send "Slumber Party Games"     "02:00" "03:00"  2 0 "🎲" "Mini Club · Deck C"         "kids"
send "Night Puzzles"           "03:00" "04:00"  3 0 "🧩" "Mini Club · Deck C"         "kids"
send "Early Birds Club"        "04:00" "05:00"  4 0 "🐦" "Mini Club · Deck C"         "kids"
send "Morning Cartoons"        "05:00" "06:00"  5 0 "📺" "Mini Club · Deck C"         "kids"
send "Breakfast Fun"           "06:00" "07:00"  6 0 "🥐" "Mini Club · Deck C"         "kids"
send "Mini Yoga"               "07:00" "08:00"  7 0 "🧘" "Beach Stage · Sunrise Deck" "kids"
send "Kids Aqua Fun"           "08:00" "09:00"  8 0 "💧" "Main Pool"                  "kids"
send "Sand Castle Contest"     "09:00" "10:00"  9 0 "🏖" "Beach Stage · Sunrise Deck" "kids"
send "Kids Mini Club"          "10:00" "11:00" 10 0 "🎨" "Mini Club · Deck C"         "kids"
send "Face Painting"           "11:00" "12:00" 11 0 "🎭" "Mini Club · Deck C"         "kids"
send "Kids Pool Party"         "12:00" "13:00" 12 0 "🌊" "Main Pool"                  "kids"
send "Junior Chef Workshop"    "13:00" "14:00" 13 0 "🍳" "Mini Club · Deck C"         "kids"
send "Mini Olympics"           "14:00" "15:00" 14 0 "🏅" "Sports Zone A"              "kids"
send "Water Balloon Fight"     "15:00" "16:00" 15 0 "💦" "Aquapark Zone"              "kids"
send "Kids Dance Class"        "16:00" "17:00" 16 0 "💃" "Beach Stage · Sunrise Deck" "kids"
send "Treasure Hunt"           "17:00" "18:00" 17 0 "🗺" "Beach Stage · Sunrise Deck" "kids"
send "Kids Show"               "18:00" "19:00" 18 0 "🎪" "Amphitheatre"               "kids"
send "Evening Games"           "19:00" "20:00" 19 0 "🎲" "Mini Club · Deck C"         "kids"
send "Mini Disco"              "20:00" "21:00" 20 0 "🪩" "Mini Club · Deck C"         "kids"
send "Bedtime Story"           "21:00" "22:00" 21 0 "📖" "Mini Club · Deck C"         "kids"
send "Night Movie"             "22:00" "23:00" 22 0 "🎬" "Mini Club · Deck C"         "kids"
send "Starry Night Club"       "23:00" "00:00" 23 0 "⭐" "Mini Club · Deck C"         "kids"

echo ""
echo "════════════════════════════════════════"
echo "  EVENING  (24 aktivite)"
echo "════════════════════════════════════════"
send "Midnight DJ Set"         "00:00" "01:00"  0 0 "🎧" "Disco & Aquapark"           "evening"
send "After Party Lounge"      "01:00" "02:00"  1 0 "🍸" "Sunset Bar · Lobby Bar"     "evening"
send "Late Night Beats"        "02:00" "03:00"  2 0 "🎵" "Disco & Aquapark"           "evening"
send "Silent Disco"            "03:00" "04:00"  3 0 "🎧" "Disco & Aquapark"           "evening"
send "Chill Out Session"       "04:00" "05:00"  4 0 "🌙" "Sunset Bar · Lobby Bar"     "evening"
send "Dawn Acoustic"           "05:00" "06:00"  5 0 "🎸" "Show Stage"                 "evening"
send "Morning Serenade"        "06:00" "07:00"  6 0 "🎶" "Panorama Deck"              "evening"
send "Breakfast Live Music"    "07:00" "08:00"  7 0 "🎵" "Main Restaurant"            "evening"
send "Pool DJ"                 "08:00" "09:00"  8 0 "🎧" "Main Pool"                  "evening"
send "Beach Party Warm-Up"     "09:00" "10:00"  9 0 "🏖" "Beach Stage · Sunrise Deck" "evening"
send "Daytime Live Band"       "10:00" "11:00" 10 0 "🎸" "Show Stage"                 "evening"
send "Acoustic Session"        "11:00" "12:00" 11 0 "🎶" "Panorama Deck"              "evening"
send "Poolside DJ"             "12:00" "13:00" 12 0 "🎧" "Main Pool"                  "evening"
send "Afternoon Show"          "13:00" "14:00" 13 0 "🎭" "Amphitheatre"               "evening"
send "Latin Dance Performance" "14:00" "15:00" 14 0 "💃" "Show Stage"                 "evening"
send "Foam & Music"            "15:00" "16:00" 15 0 "🫧" "Aquapark Zone"              "evening"
send "Sunset DJ"               "16:00" "17:00" 16 0 "🌅" "Beach Stage · Sunrise Deck" "evening"
send "Cocktail Show"           "17:00" "18:00" 17 0 "🍹" "Sunset Bar · Lobby Bar"     "evening"
send "Welcome Night Show"      "18:00" "19:00" 18 0 "✨" "Amphitheatre"               "evening"
send "Gala Dinner Music"       "19:00" "20:00" 19 0 "🎵" "Main Restaurant"            "evening"
send "Live Music – Bosphorus"  "20:00" "21:00" 20 0 "🎸" "Show Stage"                 "evening"
send "Evening Show"            "21:00" "22:00" 21 0 "✨" "Amphitheatre"               "evening"
send "DJ Night"                "22:00" "23:00" 22 0 "🎧" "Disco & Aquapark"           "evening"
send "Late Night Disco"        "23:00" "00:00" 23 0 "🪩" "Disco & Aquapark"           "evening"

echo ""
echo "✅ Tamamlandı — 72 aktivite gönderildi"
